name: Game Of Life CI 
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: compiling
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: compiling
        shell: bash
        run: |
            echo "Starting compilation"
            ls .
            bin/compile
